### ISSUE TITLE
Universal Support

### ISSUE THREAD

**Issue by oktaysenkan** [oktaysenkan/monicon#15]
I've decided to enhance the project by adding support for React, Vue, Svelte, Vanilla, React Native, and React Native Web. The primary reason behind this decision is my dissatisfaction with the Iconify official library's operation over HTTP. Therefore, I wish to rename the project from react-native-iconify to a different name.

In conjunction with this, we will transition to a monorepo structure, offering several packages:

- {package}/core
- {package}/metro
- {package}/vite
- {package}/webpack
- {package}/babel

Each of these packages will be tailored to integrate seamlessly with the respective technology, providing developers with a uniform icon library experience across multiple frameworks and platforms.

**Comment by oktaysenkan** [comment]
web-react support can be preview on [v1.1.0-universal](https://www.npmjs.com/package/react-native-iconify/v/1.1.0-universal)

**vite.config.ts**
```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: ["react-native-iconify/plugin"],
      },
    }),
  ],
});
```

**App.tsx**
```tsx
import { Iconify } from "react-native-iconify/web";
import { Iconify } from "react-native-iconify/native";
<Iconify icon="mdi:home" size={32} />
```

**Comment by TheUltDev** [comment]
@oktaysenkan Hello, how is work going on this?

For background context, I'm working on a launch of a starter kit / library for universal react native and  I use your library for native support for icons and @iconify/react for web. (https://exo.ult.dev/primitives/assets/icon)

I'd also like to hear an expansion on your criticisms on the official iconify library as I haven't run into them yet.

**Comment by oktaysenkan** [comment]
Hi, thank you. 

I like the exo, it's looking good and its documentation is awesome.

This work is still draft, i didn't code anything yet.

The main problem of `@iconify/react` is the icons blink because it works over http. Secondly it does not work in offline applications (PWA & Electron).

**Comment by TheUltDev** [comment]
I see. Thanks for the reply. I will keep an eye on this.

**Comment by oktaysenkan** [comment]
Hi, i added React Web (Vite, Next) support.

**Comment by oktaysenkan** [comment]
`react-native-iconify` has been renamed to `Monicon`.

You can find details on [Monicon Release](https://github.com/oktaysenkan/monicon/releases/tag/0.0.131)
