### ISSUE TITLE
"color" is now applied to icon background

### ISSUE THREAD

**Issue by tomas-petrovcin** [oktaysenkan/monicon#28]
[react-native]
after update to `@monicon/native`, icons are now applying "color" prop to background instead of strokes

example:
```jsx
<Monicon
  size={24}
  name="icon-park-outline:arrow-circle-right"
  color="red"
 />
```
output:
<img width="35" alt="Simulator 2024-10-07 02 48 36" src="https://github.com/user-attachments/assets/218c4529-d4d4-4518-81c1-20d5df98c9d7">

**Comment by oktaysenkan** [comment]
<img width="160" alt="Screenshot 2024-10-07 at 05 54 41" src="https://github.com/user-attachments/assets/95b98d35-a06d-4d52-b854-c01f2819aa74">

thanks for reporting, fixed in v0.0.133
