### ISSUE TITLE
Docs: adding custom icons

### ISSUE THREAD

**Issue by ljukas** [oktaysenkan/monicon#48]
We use fully custom icons designed in Figma, would be great with documentation on how to add these. Right now I cannot find any documentation on how to use icons that exists outside the specified icon sets

**Comment by oktaysenkan** [comment]
Hi, this feature is not implemented right now. ıts in my todo list.

**Comment by oktaysenkan** [comment]
Released on v0.0.153

**Documentation**

- [**Local Collections**](https://monicon-docs.vercel.app/customization/local-collections)
- [**JSON Collections**](https://monicon-docs.vercel.app/customization/json-collections)
- [**Remote Collections**](https://monicon-docs.vercel.app/customization/remote-collections)
- [**Custom Loader**](https://monicon-docs.vercel.app/customization/custom-loader)

**Comment by timmaier** [comment]
Hey how does one go about adding custom icons in react native? Does the same vite config work in the babel config?

**Comment by timmaier** [comment]
Edit turns out this is exactly how it works ^ thank you so much working well in my expo project!

**Comment by oktaysenkan** [comment]
All bundlers are supported as well. You can use like vite config.
