### ISSUE TITLE
Why don’t you declare the icons as ES Modules, so they’re fully tree-shakable?

### ISSUE THREAD

**Issue by fivaz3** [oktaysenkan/monicon#51]
You wouldn’t have to deal with the hassle of manually adding the icons you’re going to use in the vite.config.js.

Even if your library has millions of icons, all of them would be available during development, but only the ones actually used would be included in the final build shipped to the client.

**Comment by oktaysenkan** [comment]
I don’t like multiple imports for icons but i can add this feature later.

**Example usage**

```tsx
import UserIcon from "@monicon/lucide/user"
import AccountIcon from "@monicon/lucide/account"
```

**Comment by fivaz3** [comment]
thanks, it would be great

**Comment by benweier** [comment]
@oktaysenkan This would be far more preferable than adding individual icon names to the build config or unnecessarily bloating the bundle with an entire collection. I'd love to recommend we adopt Monicon within my workplace, as the standard icon solution for all our apps, but unfortunately I can't do that if the DX every time is "use an icon.. check the config"

**Comment by oktaysenkan** [comment]
I am thinking a solution for this. Metro does not provide module load function like Vite.

**Comment by oktaysenkan** [comment]
I just created the issue on metro repo

https://github.com/facebook/metro/issues/1422
